- name: vars
  hosts: localhost
  connection: local
  become: true
  vars:
    url: play.google.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL= {{url}}

    - name: task variable
      ansible.builtin.debug:
        msg: url = {{url}}
      vars:
        url: tasks.google.com
