- name: vars types
  hosts: all
  become: true
  vars:
    name: apple
    quantity: 100
    for_sale: 'true'
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: name - "{{ name }}", quantity - "{{ quantity }}"
      when: for_sale
